[2024-09-28T09:45:49.250+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-28T09:45:49.278+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_postgres_dag.create_table manual__2024-09-28T09:45:48.101620+00:00 [queued]>
[2024-09-28T09:45:49.286+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_postgres_dag.create_table manual__2024-09-28T09:45:48.101620+00:00 [queued]>
[2024-09-28T09:45:49.287+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-28T09:45:49.304+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_table> on 2024-09-28 09:45:48.101620+00:00
[2024-09-28T09:45:49.310+0000] {standard_task_runner.py:63} INFO - Started process 203 to run task
[2024-09-28T09:45:49.313+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_to_postgres_dag', 'create_table', 'manual__2024-09-28T09:45:48.101620+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/job.py', '--cfg-path', '/tmp/tmp4er7w0wf']
[2024-09-28T09:45:49.315+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask create_table
[2024-09-28T09:45:49.368+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_to_postgres_dag.create_table manual__2024-09-28T09:45:48.101620+00:00 [running]> on host c39a3d3a6c9a
[2024-09-28T09:45:49.449+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_to_postgres_dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-28T09:45:48.101620+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-28T09:45:48.101620+00:00'
[2024-09-28T09:45:49.450+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-28T09:45:49.462+0000] {sql.py:276} INFO - Executing: 
        DROP TABLE IF EXISTS sample_table;
        CREATE TABLE sample_table (
            id SERIAL PRIMARY KEY,
            name VARCHAR(50),
            age INT
        );
        
[2024-09-28T09:45:49.473+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-28T09:45:49.482+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
  File "/usr/local/lib/python3.9/functools.py", line 993, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `write_to_psql` isn't defined
[2024-09-28T09:45:49.487+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=csv_to_postgres_dag, task_id=create_table, run_id=manual__2024-09-28T09:45:48.101620+00:00, execution_date=20240928T094548, start_date=20240928T094549, end_date=20240928T094549
[2024-09-28T09:45:49.496+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task create_table (The conn_id `write_to_psql` isn't defined; 203)
[2024-09-28T09:45:49.526+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-28T09:45:49.541+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.9/site-packages/***/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-09-28T09:45:49.554+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-28T09:45:49.558+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
